import { chromium } from 'playwright';
const BASE = 'http://localhost:5199/mietblick/';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 950 } });
const errs = [];
p.on('pageerror', e => errs.push('pageerror: ' + e.message));
p.on('console', m => { if (m.type()==='error') errs.push(m.text()); });
p.on('requestfailed', r => errs.push('404/fail: ' + r.url()));
await p.goto(BASE, { waitUntil: 'networkidle' });
await p.evaluate(() => localStorage.clear());
await p.reload({ waitUntil: 'networkidle' });
await p.keyboard.press('Escape'); await p.waitForTimeout(500);
console.log('Startseite   :', await p.locator('.start-title').isVisible());
console.log('CSS geladen  :', await p.evaluate(() => getComputedStyle(document.body).backgroundColor));
await p.locator('[data-testid="open-dachau"]').click(); await p.waitForTimeout(450);
console.log('Objektseite  :', await p.locator('.page-title').innerText());
console.log('URL          :', p.url());
await p.goto(BASE + '#/inbox', { waitUntil: 'networkidle' }); await p.keyboard.press('Escape'); await p.waitForTimeout(450);
await p.locator('[data-testid="evaluate"]').click(); await p.waitForTimeout(500);
console.log('Auswertung   :', (await p.locator('.stat').first().innerText()).replace(/\n/g,' '));
await p.reload({ waitUntil: 'networkidle' }); await p.keyboard.press('Escape'); await p.waitForTimeout(600);
console.log('Nach Reload  :', (await p.locator('.page').innerText()).includes('Bewerbungen ausgewertet'));
const storage = await p.evaluate(() => { try { localStorage.setItem('__t','1'); const v = localStorage.getItem('__t'); localStorage.removeItem('__t'); return v==='1'; } catch { return false; } });
console.log('localStorage :', storage);
console.log('Favicon      :', await p.evaluate(() => document.querySelector('link[rel=icon]')?.href.slice(0,32)));
console.log('Fehler       :', errs.length ? errs.slice(0,4) : 'keine');
await b.close();
